# -*- coding: utf-8 -*-
"""Unemployment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnd3Hkli7AYWIrjrlcwZ4AGQaijv99Ol
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv("Unemployment in India.csv")

df2 = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

print(df1.head())
print(df2.head())

print(df1.info())

print(df1.isnull().sum())

print(df2.info())

print(df2.isnull().sum())

df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

df1['Date'] = pd.to_datetime(df1['Date'])

df2['Date'] = pd.to_datetime(df2['Date'])

print(df1.isnull().sum())

print(df2.isnull().sum())

df1.dropna(inplace=True)

df2.dropna(inplace=True)

print(df1.describe())

plt.figure(figsize=(10,5))

sns.histplot(
    df1['Estimated Unemployment Rate (%)'],
    bins=20,
    kde=True
)

plt.title("Distribution of Unemployment Rate")
plt.show()

state_unemployment = df1.groupby('Region')[
    'Estimated Unemployment Rate (%)'
].mean().sort_values(ascending=False)

plt.figure(figsize=(12,8))

state_unemployment.plot(kind='bar')

plt.title("Average Unemployment Rate by State")
plt.ylabel("Unemployment Rate (%)")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x='Area',
    y='Estimated Unemployment Rate (%)',
    data=df1
)

plt.title("Urban vs Rural Unemployment")
plt.show()

df1['Month'] = df1['Date'].dt.month

monthly_avg = df1.groupby('Month')[
    'Estimated Unemployment Rate (%)'
].mean()

plt.figure(figsize=(10,5))

monthly_avg.plot(marker='o')

plt.title("Monthly Unemployment Trend")
plt.ylabel("Rate (%)")

plt.grid()

plt.show()

plt.figure(figsize=(12,6))

sns.lineplot(
    data=df2,
    x='Date',
    y='Estimated Unemployment Rate (%)'
)

plt.title("Unemployment During COVID-19")
plt.xticks(rotation=45)

plt.show()

df1['Year'] = df1['Date'].dt.year

before_covid = df1[
    df1['Year'] == 2019
]['Estimated Unemployment Rate (%)'].mean()

during_covid = df2[
    'Estimated Unemployment Rate (%)'
].mean()

print("Before Covid:", before_covid)

print("During Covid:", during_covid)

covid_states = df2.groupby('Region')[
    'Estimated Unemployment Rate (%)'
].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))

covid_states.plot(kind='bar')

plt.title("Top 10 States Affected During Covid")

plt.show()

plt.figure(figsize=(8,6))

sns.heatmap(
    df1.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Matrix")

plt.show()